image: python:3.8-slim

before_script:
  - pip install -U twine
  - python setup.py sdist

pypi_publish:
  stage: deploy
  script:
    - twine upload --repository-url $PYPI_REPOSITORY_URL --username $PYPI_USER --password $PYPI_PASSWORD dist/*