stages:
  - meta
  - build

getGitMeta:
  image:
    name: alpine/git:v2.26.2
    entrypoint: [""]
  stage: meta
  script:
  - echo "REVISION=$(git rev-list --count HEAD)" >> meta.env
  artifacts:
    reports:
      dotenv: meta.env

testName:
  image: openjdk:11.0.8-jre
  stage: build
  dependencies:
  - getGitMeta
  script:
  - java -version
  - echo $REVISION
