image: python:3.8-slim

stages:
  - meta
  - deploy


getGitMeta:
  image:
    name: alpine/git:v2.26.2
    entrypoint: [""]
  stage: meta
  script:
    - echo "REVISION=$(git rev-list --count HEAD)" >> th2common/version.txt
  artifacts:
    reports:
      dotenv: th2common/version.txt


before_script:
  - pip install -U twine
  - python setup.py sdist

pypi_publish:
  stage: deploy
  dependencies:
    - getGitMeta
  script:
    - echo $REVISION
    - twine upload --repository-url $PYPI_REPOSITORY_URL --username $PYPI_USER --password $PYPI_PASSWORD dist/*