variables:
  APP_NAME: 'th2-common'
  MAJOR_VERSION: '2'
  MINOR_VERSION: '0'
  MAINTENANCE_VERSION: '0'
  BUILD_ENABLED: 'false'
  DOCKER_PUBLISH_ENABLED: 'false'
  PYPI_PUBLISH_ENABLED: 'true'

include:
  - project: 'vivarium/th2/pipelines'
    ref: master
    file: '/.gitlab-ci-python.yml'